### PR TITLE
Fix some problem, include entry and lint

### PR DESCRIPTION
**Pull request by moonrailgun**
This repo looks like have some problem which influence user develop.

Here is a checklist what i change in this PR:
* run tslint -p ./ --fix
* fix some tslint warning and error manually
* disable some tslint inline, you can fix it later
    * some problem like `max-line-length` you can fix it by formatter(for example: prettier)
* change `package.json` main field to `./out/extension.js`. The output dir of typescript compiler is `output`

> for lint error, please run `npm run lint` for detail. If you dont like the `tslint:recommended` configuration, you can modify it by yourself.

-------------------

Some Question:

Whats compiler system did you use? pure typescipt or webpack? Its looks like webpack is not work correct

### CODE REVIEW

**Comment by niudai** [comment]
I use webpack as dev-prod tool, so the main field in `package.json` cannot be `./out/extension.js`, should stay as it is. You would see two dev method in `launch.json`, one of which is using webpack.
Other tslint issues are ok, but I cannot merge this cuz you change main field incorrectly.

**Comment by niudai** [comment]
Thanks！I have seen you have polished my code, this could make code better for other developers, but should still be tested.

**Comment by moonrailgun** [comment]
Ok, webpack is also a good bundler. But I am try to launch it but its cannot work correctly by `vscode/launch.json`. And its throw error when exec `npm run develop`
```
Can't resolve './src' in XXXXX
```


Could you reopen its pr? I am change back to dist/extension.js. And its should be improved continued

**Comment by moonrailgun** [comment]
FYI, git pull request system will trace all branch change until PR closed or merged.

**Pull request closed without merging**
